<div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;border:none;border-bottom:solid #20e404 1.0pt;padding:0cm 0cm 0cm 0cm;background:white;'>
    <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;text-align:justify;background:white;border:none;padding:0cm;'><strong><span style='font-size:16px;color:black;' class="text-success">T&eacute;rminos y condiciones de transacci&oacute;nes Virtuales Promolider org SAC&nbsp;</span></strong></p>
</div>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:black;'>Las transacciones que se efect&uacute;en a trav&eacute;s plataforma educativa de Pormolider org SAC, se sujetan a los presentes t&eacute;rminos y condiciones (en lo sucesivo, T&eacute;rminos y Condiciones), as&iacute; como a la legislaci&oacute;n peruana vigente, y se entienden celebradas en el distrito La Molina, provincia y departamento de Lima, Rep&uacute;blica del Per&uacute;.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:black;'>Promolider se reserva el derecho de actualizar y/o modificar los T&eacute;rminos y Condiciones que detallamos a continuaci&oacute;n en cualquier momento, sin previo aviso. Por esta raz&oacute;n recomendamos revisar los T&eacute;rminos y Condiciones cada vez que utilice la p&aacute;gina web.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:black;'>Es requisito para comprar en el marketplace de Promolider la aceptaci&oacute;n de los t&eacute;rminos y condiciones descritas a continuaci&oacute;n. Cualquier persona que realice una transacci&oacute;n mediante este canal, declara conocer y aceptar todas y cada uno de los t&eacute;rminos y condiciones descritos a continuaci&oacute;n. Asimismo, el acceso a los servicios de la Tienda Virtual Promolider podr&iacute;a ocasionalmente verse suspendido o restringido por la realizaci&oacute;n de trabajos de mantenimiento o administraci&oacute;n de los productos ofertados.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:black;'>Tienda Virtual Promolider se compromete a realizar su mejor esfuerzo para asegurar la disponibilidad de sus servicios durante las 24 horas del d&iacute;a as&iacute; como para asegurar la ausencia de errores en cualquier transmisi&oacute;n de informaci&oacute;n que pudiera tener lugar en las transacciones; sin embargo, Tienda Virtual Promolider no se hace responsable cuando sus servicios se vean afectados por la naturaleza misma del internet.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;text-align:justify;background:white;'><strong><span class="text-success" style='font-size:16px;font-family:"Calibri Light",sans-serif;color:black;'>1. REGISTRO DEL CLIENTE O USUARIO (CLIENTE)</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:black;'>El registro del cliente en este sitio, para comprar a trav&eacute;s la tienda virtual constituye una condici&oacute;n indispensable</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:black;'>Para el registro, el cliente debe proporcionar sus datos de identificaci&oacute;n fidedignos y necesarios (como nombre completo, n&uacute;mero de documento oficial de identidad, correo electr&oacute;nico, tel&eacute;fonos, entre otros) los cuales podr&aacute;n ser validados posteriormente.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;text-align:justify;background:white;'><strong><span class="text-success" style='font-size:16px;font-family:"Calibri Light",sans-serif;color:black;'>2. CLAVE SECRETA</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:black;'>Una vez registrado, el cliente deber&aacute; ingresar su n&uacute;mero de DNI y clave de acceso para compras en Tienda Virtual Promolider, la que deber&aacute; ser de 6 d&iacute;gitos alfa-num&eacute;rico y que ser&aacute; solicitada antes de efectuar una transacci&oacute;n. Esta clave de acceso es personal e intransferible y ser&aacute; necesaria de acuerdo al canal de compras elegido por el cliente.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;text-align:justify;background:white;'><strong><span class="text-success" style='font-size:16px;font-family:"Calibri Light",sans-serif;color:black;'>3. MEDIOS DE PAGOS</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:black;'>Los medios de pago que se pueden utilizar para compras en la Tienda Virtual Promolider &nbsp;son:</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:black;'>a.- Tarjeta cr&eacute;dito &nbsp;y d&eacute;bito &nbsp; nacionales .</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:black;'>b.- Tarjetas de cr&eacute;dito y d&eacute;bito Visa.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:black;'>c. Tarjetas de cr&eacute;dito MasterCard, American Express y Diners. (Nacionales e internacionales)</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:black;'>Promolider considerar&aacute; como no v&aacute;lida la transacci&oacute;n cuando se evidencie o notifique alg&uacute;n tipo de fraude, cuando se produzca un error sist&eacute;mico que distorsione el precio de las ofertas o cuando concurra alguna otra causa justificada, y proceder&aacute; a anular la transacci&oacute;n, cancelar el producto y solicitar al banco emisor de la tarjeta para que la devoluci&oacute;n del importe comprometido.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:black;'>Los aspectos relativos al funcionamiento de las tarjetas de cr&eacute;dito aceptadas en la Tienda Virtual Promolider est&aacute;n sujetos al contrato existente entre el cliente y el banco emisor de esta, sin que Promolider tenga responsabilidad alguna sobre los aspectos se&ntilde;alados en dichos contratos. Sin perjuicio de lo antes se&ntilde;alado, para efectos de las transacciones que se realicen a trav&eacute;s de la Tienda Virtual Promolider, el cliente declara que las &oacute;rdenes de pago se emitieron y se ejecutaron en el distrito de La Molina, provincia y departamento de Lima, Rep&uacute;blica del Per&uacute;.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:black;'>La pasarela de pagos usada por Promolider en la tienda Virtual es Openpay</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;text-align:justify;background:white;'><strong><span class="text-success" style='font-size:16px;font-family:"Calibri Light",sans-serif;color:black;'>4. VALIDEZ Y PRECIO</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:black;'>Los precios exhibidos en www.promolider.org son exclusivos para las compras efectuadas en Tienda Virtual Promolider.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:black;'>Los precios de los productos consignados en la Tienda Virtual Promolider son en moneda D&oacute;lar Americano (USD.), y de igual manera los comprobantes de pago que se emiten.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;text-align:justify;background:white;'><strong><span class="text-success" style='font-size:16px;font-family:"Calibri Light",sans-serif;color:black;'>5. COMPROBANTES DE PAGO</span></strong></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:black;'>El cliente deber&aacute; decidir correctamente el tipo de documento electr&oacute;nico que solicitar&aacute; como comprobante de pago de su compra, ya que de acuerdo al Reglamento de Comprobantes de Pago aprobado por Resoluci&oacute;n de Superintendencia N&deg; 007-99/SUNAT (RCP) y al Texto &Uacute;nico Ordenado de la Ley del Impuesto General a las Ventas e Impuesto Selectivo al Consumo, aprobado mediante Decreto Supremo N&deg; 055-99-EF y normas modificatorias, no proceder&aacute; cambio alguno:</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Calibri Light",sans-serif;color:black;'>&ldquo;No existe ning&uacute;n procedimiento vigente que permita el canje de boletas de venta por facturas, m&aacute;s a&uacute;n las notas de cr&eacute;dito no se encuentran previstas para modificar al adquirente o usuario que figura en el comprobante de pago original&rdquo;.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Arial",sans-serif;color:black;'>Al aceptar estos t&eacute;rminos y condiciones, el cliente autoriza a Promolider a que env&iacute;e el comprobante electr&oacute;nico al correo electr&oacute;nico consignado en el proceso de compra.</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;text-align:justify;background:white;'><span style='font-size:16px;font-family:"Arial",sans-serif;'>&nbsp;</span></p>
<p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;'><span style='font-size:19px;line-height:107%;font-family:"Abadi",sans-serif;'>&nbsp;</span></p>
